### ISSUE TITLE
从 `.yaml` 配置文件读取 DNS 端口的方法在一些情况下有误

### ISSUE THREAD

**Issue by w568w** [410154425/AdGuardHome_magisk#5]
我的 `AdGuardHome.yaml` 内容如下：

```yaml
http:
  pprof:
    port: 6060
    enabled: false
  address: 0.0.0.0:3000
  session_ttl: 720h
users:
  - name: root
    password: $2a$10$zHcQbG4nXIzPB/Cj5M9lQ.qbQH/EZAT2wakz/sK1.b/d4ey2oqUd2
auth_attempts: 5
block_auth_min: 15
http_proxy: ""
language: zh-cn
theme: auto
dns:
  bind_hosts:
    - 0.0.0.0
  port: 5591

// ... 余下省略 ...
```

而脚本 `topdalao` 用下列字符串处理方法来硬性匹配第一个 `port:` 开头的端口号：

https://github.com/410154425/AdGuardHome_magisk/blob/269186ab508fbed5078eb4bb1457f1189cc59890/topdalao#L90

在模式 3 下，这导致其将所有 DNS 流量**导向不存在的 `127.0.0.1:6060`，使设备无法联网**。

建议考虑替换为外部工具读取 YAML 文件，例如打包一个 [`yq`](https://mikefarah.gitbook.io/yq/)，用以下方式来读取：

```bash
cat "$MODDIR/AdGuardHome.yaml" | yq '.dns.port'
```

不仅更简洁，可靠性也更高。
